export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const USER_LOADED = 'USER_LOADED';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_CUSTOMER = 'GET_CUSTOMER';
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_ERROR = 'GET_CUSTOMER_ERROR';

export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_ERROR = 'GET_CUSTOMERS_ERROR';

export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_ERROR = 'ADD_CUSTOMER_ERROR';

export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_ERROR = 'UPDATE_CUSTOMER_ERROR';

export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_ERROR = 'DELETE_CUSTOMER_ERROR';

export const GET_CUSTOMER_RECEIPTS = 'GET_CUSTOMER_RECEIPTS';
export const GET_CUSTOMER_RECEIPTS_SUCCESS = 'GET_CUSTOMER_RECEIPTS_SUCCESS';
export const GET_CUSTOMER_RECEIPTS_ERROR = 'GET_CUSTOMER_RECEIPTS_ERROR';
export const CLOSE_CUSTOMER_RECEIPTS_TABLE = 'CLOSE_CUSTOMER_RECEIPTS_TABLE';
export const SORT_CUSTOMERS = 'SORT_CUSTOMER'

//SEARCH
export const SET_SEARCH = 'SET_SEARCH';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const LOCATION_CHANGED = 'SET_LOCATION_CHANGED'

//PAGINATION
export const SET_PAGINATION_PAGE = 'SET_PAGINATION_PAGE';
export const SET_PAGINATION_ITEMS = 'SET_PAGINATION_ITEMS';
export const SET_PAGINATION_SIZE = 'SET_PAGINATION_SIZE';

//MODAL

export const SET_CONFIRMATION_MODAL_SHOW = 'SET_CONFIRMATION_MODAL_SHOW';
export const SET_CONFIRMATION_MODAL_CLOSE = 'SET_CONFIRMATION_MODAL_CLOSE';
export const SET_MODAL_SHOW = 'SET_MODAL_SHOW';
export const SET_MODAL_CLOSE = 'SET_MODAL_CLOSE';

//RECEIPTS

export const GET_RECEIPT = 'GET_RECEIPT';
export const GET_RECEIPT_SUCCESS = 'GET_RECEIPT_SUCCESS';
export const GET_RECEIPT_ERROR = 'GET_RECEIPT_ERROR';

export const GET_RECEIPTS = 'GET_RECEIPTS';
export const GET_RECEIPTS_SUCCESS = 'GET_RECEIPTS_SUCCESS';
export const GET_RECEIPTS_ERROR = 'GET_RECEIPTS_ERROR';

export const ADD_RECEIPT = 'ADD_RECEIPT';
export const ADD_RECEIPT_SUCCESS = 'ADD_RECEIPT_SUCCESS';
export const ADD_RECEIPT_ERROR = 'ADD_RECEIPT_ERROR';

export const UPDATE_RECEIPT = 'UPDATE_RECEIPT';
export const UPDATE_RECEIPT_SUCCESS = 'UPDATE_RECEIPT_SUCCESS';
export const UPDATE_RECEIPT_ERROR = 'UPDATE_RECEIPT_ERROR';

//REF 
export const GET_REF_DATA_SUCCESS = 'GET_REF_DATA_SUCCESS';
export const GET_REF_DATA_ERRORS = 'GET_REF_DATA_ERRORS';
export const ADD_REF_DATA_SUCCESS = 'ADD_REF_DATA_SUCCESS'
export const ADD_REF_DATA_ERROR = 'ADD_REF_DATA_ERROR'
export const UPDATE_REF_DATA_SUCCESS = 'UPDATE_REF_DATA_SUCCESS'
export const UPDATE_REF_DATA_ERROR = 'UPDATE_REF_DATA_ERROR'
export const DELETE_REF_DATA_SUCCESS = 'DELETE_REF_DATA_SUCCESS'
export const DELETE_REF_DATA_ERROR = 'DELETE_REF_DATA_ERROR'

    //Branch
    export const GET_REF_BRANCHES = 'GET_REF_BRANCHES';
    export const ADD_REF_BRANCHES = 'ADD_REF_BRANCHES'
    export const UPDATE_REF_BRANCHES = 'UPDATE_REF_BRANCHES'
    export const DELETE_REF_BRANCHES = 'DELETE_REF_BRANCHES'

    //Payment Reason
    export const GET_REF_PAYMENT_REASONS = 'GET_REF_PAYMENT_REASONS';
    export const ADD_REF_PAYMENT_REASONS = 'ADD_REF_PAYMENT_REASONS'
    export const UPDATE_REF_PAYMENT_REASONS = 'UPDATE_REF_PAYMENT_REASONS'
    export const DELETE_REF_PAYMENT_REASONS = 'DELETE_REF_PAYMENT_REASONS'

    //Payment Type
    export const GET_REF_PAYMENT_TYPES = 'GET_REF_PAYMENT_TYPES';
    export const ADD_REF_PAYMENT_TYPES = 'ADD_REF_PAYMENT_TYPES'
    export const UPDATE_REF_PAYMENT_TYPES = 'UPDATE_REF_PAYMENT_TYPES'
    export const DELETE_REF_PAYMENT_TYPES = 'DELETE_REF_PAYMENT_TYPES'

    //Phone Types
    export const GET_REF_PHONE_TYPES = 'GET_REF_PHONE_TYPES';
    export const ADD_REF_PHONE_TYPES = 'ADD_REF_PHONE_TYPES'
    export const UPDATE_REF_PHONE_TYPES = 'UPDATE_REF_PHONE_TYPES'
    export const DELETE_REF_PHONE_TYPES = 'DELETE_REF_PHONE_TYPES'

//USERS
export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'
export const GET_USERS_ERROR = 'GET_USERS_ERROR'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS = 'GET_USERS'
export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER = 'ADD_USER'
export const ADD_USER_ERROR = 'ADD_USER_ERROR'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'
export const SORT_USERS = 'SORT_USERS'

//DASHBOARD

export const GET_DASHBOARD_BRANCHES = 'GET_DASHBOARD_BRANCHES'
export const GET_DASHBOARD_PAYMENT_REASONS = 'GET_DASHBOARD_PAYMENT_REASONS'
export const GET_DASHBOARD_PAYMENT_TYPES = 'GET_DASHBOARD_PAYMENT_TYPES'
export const GET_DASHBOARD_DATE = 'GET_DASHBOARD_DATE'
export const GET_DASHBOARD_DATA_SUCCESS = 'GET_DASHBOARD_DATA_SUCCESS';
export const GET_DASHBOARD_DATA_ERRORS = 'GET_DASHBOARD_DATA_ERRORS';

